"""Slugify utility for generating filename slugs from display names."""

from __future__ import annotations

import re
import unicodedata


def slugify(value: str) -> str:
    """Convert a display name to a URL/filename-safe slug.

    Transliterates Unicode to ASCII, lowercases, strips non-alphanumeric
    characters (except hyphens), and collapses whitespace/hyphens.

    Matches Django's ``django.utils.text.slugify`` behavior so that slugs
    are consistent with those generated by ``generate_missing_ipdb_data.py``.
    """
    value = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode("ascii")
    value = re.sub(r"[^\w\s-]", "", value).lower()
    return re.sub(r"[-\s]+", "-", value).strip("-") or "item"
